services:
  southbound-api:
    build: .
    ports:
      - "9080:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - application-repository-network
 
networks:
  application-repository-network:
    external: true
